CREATE TABLE IF NOT EXISTS visitors (
    id VARCHAR(50) PRIMARY KEY,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    ip VARCHAR(45),
    city VARCHAR(100),
    region VARCHAR(100),
    country VARCHAR(100),
    country_code VARCHAR(10),
    latitude DECIMAL(10, 8),
    longitude DECIMAL(11, 8),
    timezone VARCHAR(50),
    isp VARCHAR(100),
    page TEXT,
    pageTitle TEXT,
    referrer TEXT,
    userAgent TEXT,
    deviceType VARCHAR(50),
    os VARCHAR(50),
    browser VARCHAR(50),
    screenResolution VARCHAR(50),
    viewportSize VARCHAR(50),
    language VARCHAR(50),
    colorDepth INT,
    pixelRatio FLOAT,
    cookiesEnabled BOOLEAN,
    doNotTrack BOOLEAN,
    advancedTracking JSONB
);
